
# Importing Basic Modules
import sys, os, time
from datetime import datetime
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
from random import randint

# Importing PyQt5 Modules
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel
from PyQt5 import QtGui
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QThread, QObject, pyqtSignal

# Defining color css for Actuator States. If you wanna change the color, then just change the RGB Values here. 
red_color = "background-color: rgb(246, 97, 81);"
green_color = "background-color: rgb(143, 240, 164);"


class Ui_MainWindow(QMainWindow, object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.navigation_tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.navigation_tab_widget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.navigation_tab_widget.setObjectName("navigation_tab_widget")
        self.dashboard_tab = QtWidgets.QWidget()
        self.dashboard_tab.setObjectName("dashboard_tab")
        self.MainFrame = QtWidgets.QFrame(self.dashboard_tab)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.progress_bar = QtWidgets.QProgressBar(self.MainFrame)
        self.progress_bar.setGeometry(QtCore.QRect(270, 480, 1600, 31))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.data_fields_list_widget = QtWidgets.QListWidget(self.MainFrame)
        self.data_fields_list_widget.setGeometry(QtCore.QRect(0, 39, 250, 1031))
        self.data_fields_list_widget.setObjectName("data_fields_list_widget")
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.data_fields_list_widget.addItem(item)
        self.current_dial = QtWidgets.QDial(self.MainFrame)
        self.current_dial.setGeometry(QtCore.QRect(930, 60, 241, 181))
        self.current_dial.setObjectName("current_dial")
        self.acc_dial = QtWidgets.QDial(self.MainFrame)
        self.acc_dial.setGeometry(QtCore.QRect(550, 80, 361, 311))
        self.acc_dial.setObjectName("acc_dial")
        self.temp_val_lbl_1 = QtWidgets.QLabel(self.MainFrame)
        self.temp_val_lbl_1.setGeometry(QtCore.QRect(590, 590, 241, 41))
        self.temp_val_lbl_1.setObjectName("temp_val_lbl_1")
        self.temp_val_lbl_2 = QtWidgets.QLabel(self.MainFrame)
        self.temp_val_lbl_2.setGeometry(QtCore.QRect(590, 630, 241, 41))
        self.temp_val_lbl_2.setObjectName("temp_val_lbl_2")
        self.temp_val_lbl_3 = QtWidgets.QLabel(self.MainFrame)
        self.temp_val_lbl_3.setGeometry(QtCore.QRect(590, 670, 241, 41))
        self.temp_val_lbl_3.setObjectName("temp_val_lbl_3")
        self.temp_val_lbl_4 = QtWidgets.QLabel(self.MainFrame)
        self.temp_val_lbl_4.setGeometry(QtCore.QRect(590, 710, 241, 41))
        self.temp_val_lbl_4.setObjectName("temp_val_lbl_4")
        self.temp_val_lbl_5 = QtWidgets.QLabel(self.MainFrame)
        self.temp_val_lbl_5.setGeometry(QtCore.QRect(590, 750, 241, 41))
        self.temp_val_lbl_5.setObjectName("temp_val_lbl_5")
        self.temp_val_lbl_6 = QtWidgets.QLabel(self.MainFrame)
        self.temp_val_lbl_6.setGeometry(QtCore.QRect(590, 790, 241, 41))
        self.temp_val_lbl_6.setObjectName("temp_val_lbl_6")
        self.temp_lbl = QtWidgets.QLabel(self.MainFrame)
        self.temp_lbl.setGeometry(QtCore.QRect(570, 530, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.temp_lbl.setFont(font)
        self.temp_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_lbl.setObjectName("temp_lbl")
        self.pres_val_lbl_2 = QtWidgets.QLabel(self.MainFrame)
        self.pres_val_lbl_2.setGeometry(QtCore.QRect(860, 630, 241, 41))
        self.pres_val_lbl_2.setObjectName("pres_val_lbl_2")
        self.pressure_lbl = QtWidgets.QLabel(self.MainFrame)
        self.pressure_lbl.setGeometry(QtCore.QRect(820, 530, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pressure_lbl.setFont(font)
        self.pressure_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_lbl.setObjectName("pressure_lbl")
        self.pres_val_lbl_3 = QtWidgets.QLabel(self.MainFrame)
        self.pres_val_lbl_3.setGeometry(QtCore.QRect(860, 670, 241, 41))
        self.pres_val_lbl_3.setObjectName("pres_val_lbl_3")
        self.pres_val_lbl_5 = QtWidgets.QLabel(self.MainFrame)
        self.pres_val_lbl_5.setGeometry(QtCore.QRect(860, 750, 241, 41))
        self.pres_val_lbl_5.setObjectName("pres_val_lbl_5")
        self.pres_val_lbl_1 = QtWidgets.QLabel(self.MainFrame)
        self.pres_val_lbl_1.setGeometry(QtCore.QRect(860, 590, 241, 41))
        self.pres_val_lbl_1.setObjectName("pres_val_lbl_1")
        self.pres_val_lbl_6 = QtWidgets.QLabel(self.MainFrame)
        self.pres_val_lbl_6.setGeometry(QtCore.QRect(860, 790, 241, 41))
        self.pres_val_lbl_6.setObjectName("pres_val_lbl_6")
        self.pres_val_lbl_4 = QtWidgets.QLabel(self.MainFrame)
        self.pres_val_lbl_4.setGeometry(QtCore.QRect(860, 710, 241, 41))
        self.pres_val_lbl_4.setObjectName("pres_val_lbl_4")
        self.actuator_box_4 = QtWidgets.QLabel(self.MainFrame)
        self.actuator_box_4.setGeometry(QtCore.QRect(310, 580, 91, 81))
        self.actuator_box_4.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.actuator_box_4.setText("")
        self.actuator_box_4.setObjectName("actuator_box_4")
        self.actuator_box_1 = QtWidgets.QLabel(self.MainFrame)
        self.actuator_box_1.setGeometry(QtCore.QRect(410, 580, 91, 81))
        self.actuator_box_1.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.actuator_box_1.setText("")
        self.actuator_box_1.setObjectName("actuator_box_1")
        self.actuator_box_2 = QtWidgets.QLabel(self.MainFrame)
        self.actuator_box_2.setGeometry(QtCore.QRect(310, 670, 91, 81))
        self.actuator_box_2.setStyleSheet("background-color: rgb(246, 97, 81);\n"
"background-color: rgb(143, 240, 164);")
        self.actuator_box_2.setText("")
        self.actuator_box_2.setObjectName("actuator_box_2")
        self.actuator_box_3 = QtWidgets.QLabel(self.MainFrame)
        self.actuator_box_3.setGeometry(QtCore.QRect(410, 670, 91, 81))
        self.actuator_box_3.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.actuator_box_3.setText("")
        self.actuator_box_3.setObjectName("actuator_box_3")
        self.actuator_lbl = QtWidgets.QLabel(self.MainFrame)
        self.actuator_lbl.setGeometry(QtCore.QRect(290, 530, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.actuator_lbl.setFont(font)
        self.actuator_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.actuator_lbl.setObjectName("actuator_lbl")
        self.launch_btn = QtWidgets.QPushButton(self.MainFrame)
        self.launch_btn.setGeometry(QtCore.QRect(1150, 550, 261, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.launch_btn.setFont(font)
        self.launch_btn.setObjectName("launch_btn")
        self.brake_btn = QtWidgets.QPushButton(self.MainFrame)
        self.brake_btn.setGeometry(QtCore.QRect(1150, 710, 591, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.brake_btn.setFont(font)
        self.brake_btn.setObjectName("brake_btn")
        self.arm_btn = QtWidgets.QPushButton(self.MainFrame)
        self.arm_btn.setGeometry(QtCore.QRect(1480, 550, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.arm_btn.setFont(font)
        self.arm_btn.setObjectName("arm_btn")
        self.current_lbl = QtWidgets.QLabel(self.MainFrame)
        self.current_lbl.setGeometry(QtCore.QRect(970, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.current_lbl.setFont(font)
        self.current_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.current_lbl.setObjectName("current_lbl")
        self.acc_lbl = QtWidgets.QLabel(self.MainFrame)
        self.acc_lbl.setGeometry(QtCore.QRect(600, 20, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.acc_lbl.setFont(font)
        self.acc_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_lbl.setObjectName("acc_lbl")
        self.comm_lbl = QtWidgets.QLabel(self.MainFrame)
        self.comm_lbl.setGeometry(QtCore.QRect(270, 770, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.comm_lbl.setFont(font)
        self.comm_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.comm_lbl.setObjectName("comm_lbl")
        self.velo_lbl = QtWidgets.QLabel(self.MainFrame)
        self.velo_lbl.setGeometry(QtCore.QRect(1240, 30, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.velo_lbl.setFont(font)
        self.velo_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.velo_lbl.setObjectName("velo_lbl")
        self.comm_status_radio_btn = QtWidgets.QRadioButton(self.MainFrame)
        self.comm_status_radio_btn.setGeometry(QtCore.QRect(360, 810, 148, 28))
        self.comm_status_radio_btn.setChecked(True)
        self.comm_status_radio_btn.setAutoExclusive(False)
        self.comm_status_radio_btn.setObjectName("comm_status_radio_btn")
        self.current_val_lbl = QtWidgets.QLabel(self.MainFrame)
        self.current_val_lbl.setGeometry(QtCore.QRect(1010, 100, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.current_val_lbl.setFont(font)
        self.current_val_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.current_val_lbl.setWordWrap(True)
        self.current_val_lbl.setObjectName("current_val_lbl")
        self.current_unit_lbl = QtWidgets.QLabel(self.MainFrame)
        self.current_unit_lbl.setGeometry(QtCore.QRect(1010, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.current_unit_lbl.setFont(font)
        self.current_unit_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.current_unit_lbl.setObjectName("current_unit_lbl")
        self.acc_unit_lbl = QtWidgets.QLabel(self.MainFrame)
        self.acc_unit_lbl.setGeometry(QtCore.QRect(670, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.acc_unit_lbl.setFont(font)
        self.acc_unit_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_unit_lbl.setObjectName("acc_unit_lbl")
        self.acc_val_lbl = QtWidgets.QLabel(self.MainFrame)
        self.acc_val_lbl.setGeometry(QtCore.QRect(660, 160, 141, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.acc_val_lbl.setFont(font)
        self.acc_val_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_val_lbl.setWordWrap(True)
        self.acc_val_lbl.setObjectName("acc_val_lbl")
        self.velo_dial = QtWidgets.QDial(self.MainFrame)
        self.velo_dial.setGeometry(QtCore.QRect(1180, 90, 361, 311))
        self.velo_dial.setObjectName("velo_dial")
        self.velo_val_lbl = QtWidgets.QLabel(self.MainFrame)
        self.velo_val_lbl.setGeometry(QtCore.QRect(1290, 170, 141, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.velo_val_lbl.setFont(font)
        self.velo_val_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.velo_val_lbl.setWordWrap(True)
        self.velo_val_lbl.setObjectName("velo_val_lbl")
        self.velo_unit_lbl = QtWidgets.QLabel(self.MainFrame)
        self.velo_unit_lbl.setGeometry(QtCore.QRect(1300, 260, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.velo_unit_lbl.setFont(font)
        self.velo_unit_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.velo_unit_lbl.setObjectName("velo_unit_lbl")
        self.status_radio_btn_2 = QtWidgets.QRadioButton(self.MainFrame)
        self.status_radio_btn_2.setGeometry(QtCore.QRect(1700, 40, 148, 28))
        self.status_radio_btn_2.setCheckable(True)
        self.status_radio_btn_2.setChecked(False)
        self.status_radio_btn_2.setAutoRepeat(False)
        self.status_radio_btn_2.setAutoExclusive(False)
        self.status_radio_btn_2.setObjectName("status_radio_btn_2")
        self.status_radio_btn_3 = QtWidgets.QRadioButton(self.MainFrame)
        self.status_radio_btn_3.setGeometry(QtCore.QRect(1560, 70, 148, 28))
        self.status_radio_btn_3.setCheckable(True)
        self.status_radio_btn_3.setChecked(True)
        self.status_radio_btn_3.setAutoExclusive(False)
        self.status_radio_btn_3.setObjectName("status_radio_btn_3")
        self.status_radio_btn_1 = QtWidgets.QRadioButton(self.MainFrame)
        self.status_radio_btn_1.setGeometry(QtCore.QRect(1560, 40, 148, 28))
        self.status_radio_btn_1.setChecked(True)
        self.status_radio_btn_1.setAutoExclusive(False)
        self.status_radio_btn_1.setObjectName("status_radio_btn_1")
        self.status_radio_btn_4 = QtWidgets.QRadioButton(self.MainFrame)
        self.status_radio_btn_4.setGeometry(QtCore.QRect(1700, 70, 148, 28))
        self.status_radio_btn_4.setChecked(True)
        self.status_radio_btn_4.setAutoExclusive(False)
        self.status_radio_btn_4.setObjectName("status_radio_btn_4")
        self.power_slider = QtWidgets.QSlider(self.MainFrame)
        self.power_slider.setGeometry(QtCore.QRect(1760, 760, 131, 21))
        self.power_slider.setOrientation(QtCore.Qt.Horizontal)
        self.power_slider.setObjectName("power_slider")
        self.power_lbl = QtWidgets.QLabel(self.MainFrame)
        self.power_lbl.setGeometry(QtCore.QRect(1740, 720, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.power_lbl.setFont(font)
        self.power_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.power_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.power_lbl.setObjectName("power_lbl")
        self.checkbox_1 = QtWidgets.QCheckBox(self.MainFrame)
        self.checkbox_1.setGeometry(QtCore.QRect(1150, 510, 141, 28))
        self.checkbox_1.setObjectName("checkbox_1")
        self.checkbox_2 = QtWidgets.QCheckBox(self.MainFrame)
        self.checkbox_2.setGeometry(QtCore.QRect(1490, 510, 151, 28))
        self.checkbox_2.setObjectName("checkbox_2")
        self.error_val_lbl = QtWidgets.QLabel(self.MainFrame)
        self.error_val_lbl.setGeometry(QtCore.QRect(1760, 540, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(55)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.error_val_lbl.setFont(font)
        self.error_val_lbl.setStyleSheet("color: rgb(237, 51, 59);")
        self.error_val_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_val_lbl.setObjectName("error_val_lbl")
        self.error_lbl = QtWidgets.QLabel(self.MainFrame)
        self.error_lbl.setGeometry(QtCore.QRect(1750, 640, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.error_lbl.setFont(font)
        self.error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lbl.setObjectName("error_lbl")
        self.status_radio_btn_5 = QtWidgets.QRadioButton(self.MainFrame)
        self.status_radio_btn_5.setGeometry(QtCore.QRect(1560, 100, 148, 28))
        self.status_radio_btn_5.setChecked(True)
        self.status_radio_btn_5.setAutoExclusive(False)
        self.status_radio_btn_5.setObjectName("status_radio_btn_5")
        self.data_field_lbl = QtWidgets.QLabel(self.MainFrame)
        self.data_field_lbl.setGeometry(QtCore.QRect(0, 0, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.data_field_lbl.setFont(font)
        self.data_field_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.data_field_lbl.setObjectName("data_field_lbl")
        self.random_btn_1 = QtWidgets.QPushButton(self.MainFrame)
        self.random_btn_1.setGeometry(QtCore.QRect(1150, 840, 154, 32))
        self.random_btn_1.setObjectName("random_btn_1")
        self.random_btn_2 = QtWidgets.QPushButton(self.MainFrame)
        self.random_btn_2.setGeometry(QtCore.QRect(1350, 840, 154, 32))
        self.random_btn_2.setObjectName("random_btn_2")
        self.random_btn_3 = QtWidgets.QPushButton(self.MainFrame)
        self.random_btn_3.setGeometry(QtCore.QRect(1540, 840, 154, 32))
        self.random_btn_3.setObjectName("random_btn_3")
        self.random_btn_4 = QtWidgets.QPushButton(self.MainFrame)
        self.random_btn_4.setGeometry(QtCore.QRect(1730, 840, 154, 32))
        self.random_btn_4.setObjectName("random_btn_4")
        self.navigation_tab_widget.addTab(self.dashboard_tab, "")
        self.graph_tab = QtWidgets.QWidget()
        self.graph_tab.setObjectName("graph_tab")
        self.navigation_tab_widget.addTab(self.graph_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.random_btn_1.clicked.connect(self.runLongTask_with_thread_1)
        self.random_btn_2.clicked.connect(self.gen_Graph)
        self.random_btn_3.clicked.connect(self.runLongTask_with_thread_2)



        # Creating a layout for graphs. 
        self.layout_widget = QtWidgets.QWidget(self.graph_tab)
        self.layout_widget.setGeometry(QtCore.QRect(0, 0, 1920, 1000))
        self.layout_widget.setObjectName("layout_widget")
        
        # Adding vertical Layout to graphs. 
        self.vertical_layout = QtWidgets.QVBoxLayout(self.layout_widget)
        self.vertical_layout.setContentsMargins(50, 0, 50, 50)
        self.vertical_layout.setObjectName("vertical_layout")
        
        # Creating Current graph and Acceleration Graph widgets. 
        font = QtGui.QFont()
        font.setPointSize(22)
        self.velo_graph_lbl = QtWidgets.QLabel(self.layout_widget)
        self.velo_graph_lbl.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.velo_graph_lbl.setFont(font)
        self.velo_graph_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.velo_graph_lbl.setObjectName("velo_graph_lbl")
        self.velo_graph_lbl.setText("Current Live Graph")
        
        # Creating Current graph and Acceleration Graph widgets. 
        self.acc_graph_lbl = QtWidgets.QLabel(self.layout_widget)
        self.acc_graph_lbl.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.acc_graph_lbl.setFont(font)
        self.acc_graph_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_graph_lbl.setObjectName("acc_graph_lbl")
        self.acc_graph_lbl.setText("Acceleration Live Graph")
        

        # Creating the Graph
        
        self.velo_graph_pg_widget = pg.PlotWidget()

        # Demo Data
        self.x = list(range(100))  # 100 time points
        self.y = [randint(0,100) for _ in range(100)]  # 100 data points

        self.velo_graph_pg_widget.setBackground('black')
        self.velo_graph_pg_widget.showGrid(True, True)
        pen_1 = pg.mkPen(color='#11c2c4', width=2)
        self.velo_data_line =  self.velo_graph_pg_widget.plot(self.x, self.y, pen=pen_1)
        
        self.acc_graph_pg_widget = pg.PlotWidget()
        self.vertical_layout.addWidget(self.acc_graph_pg_widget)

        self.x1 = list(range(100))  # 100 time points
        self.y1 = [randint(0,50) for _ in range(100)]  # 100 data points

        self.acc_graph_pg_widget.setBackground('black')
        self.acc_graph_pg_widget.showGrid(True, True)
        pen_2 = pg.mkPen(color='#ec8734', width = 2)
        self.acc_data_line =  self.acc_graph_pg_widget.plot(self.x1, self.y1, pen=pen_2)
        

        
        self.vertical_layout.addWidget(self.velo_graph_lbl)
        self.vertical_layout.addWidget(self.velo_graph_pg_widget)
        self.vertical_layout.addWidget(self.acc_graph_lbl)
        self.vertical_layout.addWidget(self.acc_graph_pg_widget)

        self.retranslateUi(MainWindow)
        self.navigation_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.data_fields_list_widget.isSortingEnabled()
        self.data_fields_list_widget.setSortingEnabled(False)
        item = self.data_fields_list_widget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.data_fields_list_widget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.data_fields_list_widget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.data_fields_list_widget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.data_fields_list_widget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.data_fields_list_widget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.data_fields_list_widget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        self.data_fields_list_widget.setSortingEnabled(__sortingEnabled)
        self.temp_val_lbl_1.setText(_translate("MainWindow", "Temperature Value 1"))
        self.temp_val_lbl_2.setText(_translate("MainWindow", "Temperature Value 2"))
        self.temp_val_lbl_3.setText(_translate("MainWindow", "Temperature Value 3"))
        self.temp_val_lbl_4.setText(_translate("MainWindow", "Temperature Value 4"))
        self.temp_val_lbl_5.setText(_translate("MainWindow", "Temperature Value 5"))
        self.temp_val_lbl_6.setText(_translate("MainWindow", "Temperature Value 6"))
        self.temp_lbl.setText(_translate("MainWindow", "Temperature"))
        self.pres_val_lbl_2.setText(_translate("MainWindow", "Pressure Value 2"))
        self.pressure_lbl.setText(_translate("MainWindow", "Pressure"))
        self.pres_val_lbl_3.setText(_translate("MainWindow", "Pressure Value 3"))
        self.pres_val_lbl_5.setText(_translate("MainWindow", "Pressure Value 5"))
        self.pres_val_lbl_1.setText(_translate("MainWindow", "Pressure Value 1"))
        self.pres_val_lbl_6.setText(_translate("MainWindow", "Pressure Value 6"))
        self.pres_val_lbl_4.setText(_translate("MainWindow", "Pressure Value 4"))
        self.actuator_lbl.setText(_translate("MainWindow", "Actuator States"))
        self.launch_btn.setText(_translate("MainWindow", "Launch"))
        self.brake_btn.setText(_translate("MainWindow", "Brake"))
        self.arm_btn.setText(_translate("MainWindow", "Arm"))
        self.current_lbl.setText(_translate("MainWindow", "Current"))
        self.acc_lbl.setText(_translate("MainWindow", "Acceleration"))
        self.comm_lbl.setText(_translate("MainWindow", "Communication State"))
        self.velo_lbl.setText(_translate("MainWindow", "Velocity"))
        self.comm_status_radio_btn.setText(_translate("MainWindow", "Status"))
        self.current_val_lbl.setText(_translate("MainWindow", "23.52"))
        self.current_unit_lbl.setText(_translate("MainWindow", "mA"))
        self.acc_unit_lbl.setText(_translate("MainWindow", "m/s/s"))
        self.acc_val_lbl.setText(_translate("MainWindow", "11.12"))
        self.velo_val_lbl.setText(_translate("MainWindow", "49.22"))
        self.velo_unit_lbl.setText(_translate("MainWindow", "m/s"))
        self.status_radio_btn_2.setText(_translate("MainWindow", "Status 2"))
        self.status_radio_btn_3.setText(_translate("MainWindow", "Status 3"))
        self.status_radio_btn_1.setText(_translate("MainWindow", "Status 1"))
        self.status_radio_btn_4.setText(_translate("MainWindow", "Status 4"))
        self.power_lbl.setText(_translate("MainWindow", "Power"))
        self.checkbox_1.setText(_translate("MainWindow", "Check box 1"))
        self.checkbox_2.setText(_translate("MainWindow", "Check Box 2"))
        self.error_val_lbl.setText(_translate("MainWindow", "04"))
        self.error_lbl.setText(_translate("MainWindow", "Error"))
        self.status_radio_btn_5.setText(_translate("MainWindow", "Status 5"))
        self.data_field_lbl.setText(_translate("MainWindow", "Data Fields"))
        self.random_btn_1.setText(_translate("MainWindow", "Demo"))
        self.random_btn_2.setText(_translate("MainWindow", "Graph"))
        self.random_btn_3.setText(_translate("MainWindow", "Button 3"))
        self.random_btn_4.setText(_translate("MainWindow", "Button 4"))
        self.navigation_tab_widget.setTabText(self.navigation_tab_widget.indexOf(self.dashboard_tab), _translate("MainWindow", "Dashboard"))
        self.navigation_tab_widget.setTabText(self.navigation_tab_widget.indexOf(self.graph_tab), _translate("MainWindow", "Graphs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
